services:
    proophdo.default_controller:
        class: Prooph\AppBundle\Controller\DefaultController
        arguments: ['@templating']

    proophdo.user_list_controller:
        class: Prooph\AppBundle\Controller\UserListController
        arguments: ['@templating', '@proophdo.todo_projection.user_finder']

    proophdo.user_registratrion_controller:
        class: Prooph\AppBundle\Controller\UserRegistrationController
        arguments: ['@templating']

    proophdo.user_todo_list_controller:
        class: Prooph\AppBundle\Controller\UserTodoListController
        arguments: ['@templating', '@proophdo.todo_projection.user_finder', '@proophdo.todo_projection.todo_finder']

    proophdo.user_todo_form_controller:
        class: Prooph\AppBundle\Controller\UserTodoFormController
        arguments: ['@templating', '@proophdo.todo_projection.user_finder']

    proophdo.api_command_controller:
        class: Prooph\AppBundle\Controller\ApiCommandController
        arguments: ['@prooph_service_bus.todo_command_bus', '@prooph_service_bus.message_factory']

    proophdo.register_user_handler:
        class: Prooph\ProophessorDo\Model\User\Handler\RegisterUserHandler
        arguments: ['@user_collection']

    proophdo.post_todo_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\PostTodoHandler
        arguments: ['@user_collection', '@todo_list']

    proophdo.mark_todo_as_done_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\MarkTodoAsDoneHandler
        arguments: ['@todo_list']

    proophdo.reopen_todo_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\ReopenTodoHandler
        arguments: ['@todo_list']

    proophdo.add_deadline_to_todo_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\AddDeadlineToTodoHandler
        arguments: ['@todo_list']

    proophdo.add_reminder_to_todo_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\AddReminderToTodoHandler
        arguments: ['@todo_list']

    proophdo.mark_todo_expired_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\MarkTodoAsExpiredHandler
        arguments: ['@todo_list']

    proophdo.remind_todo_assignee_handler:
        class: Prooph\ProophessorDo\Model\Todo\Handler\RemindTodoAssigneeHandler
        arguments: ['@todo_list']

    proophdo.twig.extension.riot_tag:
        class:        Prooph\AppBundle\Twig\RiotTag
        tags:
             - { name: 'twig.extension' }

    proophdo.todo_notify_event_listener:
        class: Prooph\AppBundle\EventListener\TodoNotifyListener
        arguments: ['@prooph_service_bus.todo_command_bus', '@proophdo.todo_projection.todo_finder','@logger']
        tags:
             - { name: kernel.event_subscriber }

    proophdo.process_manager.send_todo_deadline_mailer:
        class: Prooph\ProophessorDo\ProcessManager\SendTodoDeadlineExpiredMailSubscriber
        arguments: ['@proophdo.todo_projection.user_finder','@proophdo.todo_projection.todo_finder','@mailer','@logger']